services:
  mysql:
    image: mysql:8.0.32  # 使用稳定的 8.0 版本（8.4 版本起不来）
    container_name: mysql-server
    restart: always
    pull_policy: never  # 可选，不自动拉取镜像省流量
    environment:
      - MYSQL_ROOT_PASSWORD=iboot@2025  # root密码
      - MYSQL_DATABASE=ibootdb  # 默认创建的数据库名
      - TZ=Asia/Shanghai  # 时区设置
    network_mode: host  # 使用主机网络模式，可以通过 localhost 访问宿主机服务
    # 使用 host 网络模式时，不需要映射端口，因为容器直接使用宿主机端口
    #ports:
    #  - "3306:3306"  # 端口映射
    volumes:
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf  # 配置文件挂载
      - ./data:/var/lib/mysql  # 数据目录挂载
      - ./logs:/var/log/mysql  # 日志目录挂载
    command: --default-authentication-plugin=mysql_native_password  # 允许使用传统密码认证方式
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-piboot@2025"]
      interval: 10s
      timeout: 5s
      retries: 5 