services:
  openresty:
    image: openresty/openresty:1.27.1.2-alpine
    container_name: openresty
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/usr/local/openresty/nginx/logs
      - ./html:/usr/local/openresty/nginx/html
      - ./lua:/usr/local/openresty/nginx/lua
    networks:
      - openresty-network

networks:
  openresty-network:
    driver: bridge 