services:
  redis:
    image: redis:latest  # 官方镜像
    pull_policy: never  # 可选，不自动拉取镜像省流量
    container_name: redis-server  # 自定义容器名
    restart: always  # 开机自启核心配置
    ports:
      - "6379:6379"  # 映射宿主机6379→容器6379
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf  # 挂载自定义配置
      - ./data:/data  # 持久化数据目录
      - ./logs:/var/log/redis  # 日志目录（可选）
    command: redis-server /usr/local/etc/redis/redis.conf  # 加载自定义配置